version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results

workflows:
  ci:
    jobs:
      - test
